[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
fs_permissions = [
  { access = "read-write", path = "./deployments" },
  { access = "read-write", path = "./testnet-e2e" },
]

[rpc_endpoints]
robinhood_testnet = "${ROBINHOOD_TESTNET_RPC_URL}"

[etherscan]
robinhood_testnet = { key = "empty", chain = 46630, url = "https://explorer.testnet.chain.robinhood.com/api/" }

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 100 }
