[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
cache_path = "cache"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 100 }
